module.exports = [
  'Advertising',
  'Automotives',
  'Body and Soul',
  'Books',
  'Collectibles',
  'Computers',
  'Crypto Coins',
  'Crypto Mining',
  'Digital Goods',
  'Electronics',
  'Entertainment',
  'Fashion',
  'Fiat',
  'Food and Beverage',
  'Home & Garden',
  'Industrial',
  'NSFW',
  'Precious Metals',
  'Printed Media',
  'Real Estate',
  'Services',
  'Sports & Hobbies',
  'Vouchers & Gift Cards',
  'Web, IT & Support'
]