module.exports = [
  'Advertising',
  'Automotives',
  'Books',
  'Collectibles',
  'Computers',
  'Cryptocurrency',
  'Digital Goods',
  'Electronics',
  'Entertainment',
  'Fashion',
  'Fiat',
  'Food and Beverage',
  'Home & Garden',
  'Industrial',
  'NSFW',
  'Other',
  'Precious Metals',
  'Printed Media',
  'Real Estate',
  'Services',
  'Sports & Hobbies',
  'Vouchers & Gift Cards',
  'Web'
]